version: '3.8'

services:
  build:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm install && npm run build

  test:
    build:
      context: .
      dockerfile: Dockerfile1
    depends_on:
      - build
    command: npm test
